AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-structured-logs

  Silly example that shows how to do structure logging inside lambda functions.

Parameters:
  AppName:
    Type: String
    Default: lambda-structured-logs

Globals:
  Function:
    Timeout: 3
    Runtime: python3.8
    Architectures:
      - arm64

Resources:
  ProgressLoggerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AppName}-progressLogger
      CodeUri: progress_logger/
      Handler: app.lambda_handler

  LatencyLoggerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AppName}-latencyLogger
      CodeUri: latency_logger/
      Handler: app.lambda_handler

Outputs:
  ProgressLoggerFunction:
    Description: "ProgressLoggerFunction Name"
    Value: !Ref ProgressLoggerFunction
  LatencyLoggerFunction:
    Description: "LatencyLoggerFunction Name"
    Value: !Ref LatencyLoggerFunction
